### ISSUE TITLE
Error configuring bootstrap -- ERROR: input isn't valid multihash

### ISSUE THREAD

**Issue by ScienceNoBorders** [ipfs-shipyard/gomobile-ipfs#111]
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/37797698/154613936-3fabf0a6-c9f9-4ddf-9994-7209b3f9bf9c.png">

**Comment by jefft0** [comment]
Hello @ScienceNoBorders . We are reviewing old issue. Are you still working on this project and getting this error?

**Comment by jefft0** [comment]
No more questions from poster. Closing.
