### ISSUE TITLE
Build fails with "You must specify a URL for a Maven repository"

### ISSUE THREAD

**Issue by makeworld-the-better-one** [ipfs-shipyard/gomobile-ipfs#113]
The current build fails with the error `You must specify a URL for a Maven repository`. This is fixed by adding `bintray_url` to `Manifest.yml`. See https://github.com/ipfs-shipyard/gomobile-ipfs/pull/106/commits/c14bbe2d601db1fbdf59c94135b49e9d244e48ef for an example of this happening.

This is fixed in #106, which is created to fix a different issue but also fixes this one.

**Comment by ScienceNoBorders** [comment]
I solved it by installing the Flutter

**Comment by jefft0** [comment]
Hello @makeworld-the-better-one . As mentioned in PR #106, a similar change was merged to master. Does this fix your problem?

**Comment by makeworld-the-better-one** [comment]
I am no longer working this this project, sorry. I assume this would be fixed if a similar change is merged. Feel free to close.

**Comment by jefft0** [comment]
OK. Thanks for the reply.
