### ISSUE TITLE
make build_core.ios report an error

### ISSUE THREAD

**Issue by DarknessFall** [ipfs-shipyard/gomobile-ipfs#115]
In the Makefile,
<img width="1210" alt="CleanShot 2022-03-30 at 18 50 35@2x" src="https://user-images.githubusercontent.com/7892335/160815160-400ea852-7c7e-4b63-aa2f-3cf85ebab560.png">
If I remove the maccatalyst target it will works, or else it will report an clang error:
clang: error: invalid version number in '-target arm64-apple-ios13.0-macabi'

**Comment by jefft0** [comment]
I confirm this build error on macOS 12 with Xcode 13.4.1.  As mentioned,`make build_core.ios` prints:

    clang: error: invalid version number in '-target arm64-apple-ios13.0-macabi'

And as mentioned, it builds if you remove the maccatalyst target [in the Makefile](https://github.com/ipfs-shipyard/gomobile-ipfs/blob/048c1e8721f64f968ff04b14b76d654bceb4499d/packages/Makefile#L138). 

But it builds correctly (with maccatalyst) on macOS 11 with xcode 13.2.1 . @DarknessFall , what is your macOS and Xcode version?

**Comment by jefft0** [comment]
No more questions. Closing as resolved.
