### ISSUE TITLE
[FEATURE]: Support go 1.18

### ISSUE THREAD

**Issue by jefft0** [ipfs-shipyard/gomobile-ipfs#119]
With Go 1.18 installed, in `packages`, `make test` prints:

    ../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.24.0/internal/qtls/go118.go:6:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration

Other packages like Berty now build on go 1.18. To use gomobile-ipfs, it needs to support 1.18.

**Comment by WesleyBatista** [comment]
Experienced the same issue and got the build working without changing my global go installation with this:
```
go install golang.org/dl/go1.17.11@latest
go1.17.11 download
GOMOBILE="go1.17.11 run golang.org/x/mobile/cmd/gomobile" make build_demo.android
```

As a side note: [lucas-clemente/quic-go](https://github.com/lucas-clemente/quic-go/releases) added support to go 1.18 on [v0.26.0](https://github.com/lucas-clemente/quic-go/releases/tag/v0.26.0).
