### ISSUE TITLE
Could not find ipfs.gomobile:core:0.0.42-dev.

### ISSUE THREAD

**Issue by ndungudedan** [ipfs-shipyard/gomobile-ipfs#127]
### Asking a question, not reporting a bug

- [X] This question is not about a bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Question

Trying to build the android example but I get the following error 
Could not find ipfs.gomobile:core:0.0.42-dev.

### Context

Cannot build android example app

**Comment by jefft0** [comment]
Hello @ndungudedan . What commands did you enter to build?

**Comment by ndungudedan** [comment]
@jefft0 I haven`t entered any commands. I also can`t find documentation referencing that.

**Comment by jefft0** [comment]
Are you trying to build the Android or iOS version? What steps did you do? (If Android, did you open Android Studio? Which folder?)

**Comment by jefft0** [comment]
If you are building in Android Studio, first you must build the Go core. In a terminal, enter:
```
cd packages
make build_core.android
```

**Comment by jefft0** [comment]
Please see the questions above. If we don't hear from you, this issue will be closed as inactive in 14 days.

**Comment by kf7mxe** [comment]
I had the same problem but when I run `make build_core.android` in the packages directory I get this error 
`------------------------------------
      Go: installing modules        
------------------------------------
go mod download
make: go: No such file or directory
make: *** [Makefile:362: run] Error 127
`

**Comment by jefft0** [comment]
@kf7mxe , you need to install Go 1.17 from https://go.dev/dl . Then set environment variables:

    export GOPATH="$HOME/go"
    export PATH="$PATH:$GOPATH/bin"

**Comment by jefft0** [comment]
Hello @JavaMousekin . I created detailed install instructions. We are still improving them and will merge into gomobile-ipfs master soon. Can you please look at the instructions? Is your platform listed? https://github.com/jefft0/gomobile-ipfs/blob/add-INSTALL/INSTALL.md

**Comment by JavaMousekin** [comment]
Hi @jefft0 appreciate your effort, that is really helpful guide, but now I'm facing the next error: Error: [Errno 2] No such file or directory: '/mnt/c/Users/Mariya/BlockchainProjects/gomobile-ipfs/packages/build/android/intermediates/core/core-sources.jar'on Windows 11 now, but running everything using Ubuntu terminal. Following the steps you provided, I'm getting the next error:

**Comment by jefft0** [comment]
Are you using Windows Subsystem for Linux? What is the Ubuntu version?

**Comment by JavaMousekin** [comment]
Yes, it's Ubuntu 20.04.5 LTS

**Comment by jefft0** [comment]
I tried on WSL. A requirement is to install and run Android Studio. When I try to launch it, I get the error "Unable to detect graphics environment". Are you able to launch Android Studio?

**Comment by JavaMousekin** [comment]
Well, I installed Android Studio to the Windows machine itself and pass /mnt/...-like paths to the env variables.

**Comment by jefft0** [comment]
I don't think that will work. Need the Linux executables for NDK, etc.

**Comment by jefft0** [comment]
Either figure out how to run Android Studio from WSL (I haven't researched this online) or run Ubuntu in a virtual machine like Virtual Box.

**Comment by JavaMousekin** [comment]
I faced some errors related to the NDK during struggling with this build process before, but after setting ANDROID_NDK_HOME to /mnt/.. directory they have vanished.
Any way, I'll try with VB, and post my updates here.
Thank u!

**Comment by jefft0** [comment]
Thanks. Let us know.

**Comment by JavaMousekin** [comment]
Hello @jefft0, so I tried to do the same on Ubuntu 22.04:

**Comment by JavaMousekin** [comment]
Hello @jefft0 I did what you suggested, but now facing another issue, seems some verion missmatch again, please advise what should I update or downgrade?

**Comment by jefft0** [comment]
Did you set the environment variables for Ubuntu as shown here?
https://github.com/jefft0/gomobile-ipfs/blob/add-INSTALL/INSTALL.md#user-content-build-for-android

Especially important is JAVA_HOME. Do you have a jre at /usr/local/android-studio/jre ?

**Comment by JavaMousekin** [comment]
@jefft0 your guess was right, I didn't set them properly at first, that was an issue. 
Please note, usr/local/android-studio/jre contains version 11 by default and it causes another issue:
`option --boot-class-path not allowed with target 11` 
So I had to install JDK version 1.8, and set it to the JAVA_HOME.
Finally it works now, thanks a lot for your help!
