### ISSUE TITLE
[gomobile-lib] implement a cleaner workaround for DNS resolver

### ISSUE THREAD

**Issue by aeddi** [ipfs-shipyard/gomobile-ipfs#19]
DNS Lookup does not work by default with gomobile on Android and iOS (only on physical device). We needed to find a workaround until [this golang issue](https://github.com/golang/go/issues/8877) is fixed.

At the moment we are using [this method](https://gist.github.com/cs8425/107e01a0652f1f1f6e033b5b68364b5e) which is very hacky.

We could instead:
- Define a go interface containing a LookupTXT method
- Implement it in Java (using [DnsResolver](https://developer.android.com/reference/android/net/DnsResolver)) and Swift (using [DNSServiceQueryRecord](https://developer.apple.com/documentation/dnssd/1804747-dnsservicequeryrecord))
- Find a clean way to override the default go-ipfs [DNSResolver](https://github.com/ipfs/go-ipfs/blob/f97ed7da47d8d8332e5f56867b18648967eeeee5/namesys/dns.go#L20)

**Comment by moul** [comment]
cc @steeve

**Comment by steeve** [comment]
Just enable CGo and let it use the CGo resolver instead. Since CGo is needed anyway when doing `gomobile bind` it's not really any different build wise.

I thought that `gomobile bind` did it but you can try to add `CGO_ENABLED=1` to the env or disable the build tag `netgo`.

**Comment by aeddi** [comment]
Fixed by #130 using this workaround: https://github.com/ipfs-shipyard/gomobile-ipfs/pull/130/commits/86863cfce316360ffab477e54ec9b29b266ca82a#diff-04399ac2eacd4034b3100cde433ad52c1eb223ed9dfb73545c869f92ce812b0fR39-R50
