### ISSUE TITLE
Add Lead Maintainers

### ISSUE THREAD

**Issue by momack2** [ipfs-shipyard/gomobile-ipfs#27]
Add Berty team (https://github.com/orgs/ipfs-shipyard/teams/berty/members minus Alan) as lead maintainers for this repo!

**Comment by moul** [comment]
@momack2 updated the README.md file in #28 

Is there anything else to do?

Btw, message to other contributors: we are more than open to having new co-maintainers on this project, feel free to reply to this issue if you want to contribute more and officially become a co-lead maintainer
