### ISSUE TITLE
Is there any policy/strategy for choosing a CI solution on the ipfs-shipyard organization?

### ISSUE THREAD

**Issue by moul** [ipfs-shipyard/gomobile-ipfs#29]
We plan to add CI rules that build different artifacts: .apk for Android and .ipa for iOS

To build iOS artifacts, we need to have OS X hosts with Xcode installed

From what I can see, other ipfs-shipyard are using mostly Travis and CircleCI, and projects that require OS X are only using Travis:

* https://github.com/ipfs-shipyard/ipfs-companion/blob/8e2eaeeeec05797b166e0ac2e149e61c4527bf61/.travis.yml#L14
* https://github.com/ipfs-shipyard/ipfs-desktop/blob/92fcdd024caeaeeec864171f49a409dd0b2e3eb8/.travis.yml#L11-L13
* https://github.com/ipfs-shipyard/js-ipfs-http-client-lite/blob/b04523834f9a17275c7c076de6bd505af3756f63/.travis.yml#L14
* https://github.com/ipfs-shipyard/ipfs-pubsub-room/blob/b8556eccfa51c4d7110090f40fd6c934621aa8cf/.travis.yml#L17
* https://github.com/ipfs-shipyard/js-hamt-sharding/blob/23566a1215ab83c77c5cbd0037de3781279393b2/.travis.yml#L13
* https://github.com/ipfs-shipyard/service-worker-gateway/blob/1715faa70879418240ad3e4cf7237d060de60d37/.travis.yml#L13

Is it just a coincidence or is it expected to use Travis when having OS X builds to do?

Maybe we can update a CONTRIBUTING.md file with this info, feel free to indicate me the most appropriate place

**Comment by moul** [comment]
cc @Stebalien @alanshaw

**Comment by olizilla** [comment]
Use the CI tool that works best for the project. Across all the orgs, we mainly use circleci, so if that works for you, go for it! For the desktop electron app, we use travis for linux and osx builds and appvayor for windows.
