### ISSUE TITLE
GitHub Actions: deprecating set-env and add-path  

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/gomobile-ipfs#60]
Seems that GitHub will remove `set-env` at some point, and that will break your CI:

> Action and workflow authors who are setting environment variables via STDOUT should update any usage of the `set-env` and `add-path` workflow commands to use the new environment files.

Details: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

cc @aeddi (lmk if you need help with migrating)

**Comment by gfanton** [comment]
This issue is not valid, since it doesn't look like we are using set-env anymore
