### ISSUE TITLE
Move repo into ipfs or ipfs-shipyard

### ISSUE THREAD

**Issue by parkan** [ipfs-shipyard/gomobile-ipfs#7]
Following up from the email thread and looping in @Stebalien. Let's move this repo into an ipfs-related org so we can get more eyes on the discussion + code.

There are two choices:
- **Move into [ipfs-shipyard](https://github.com/ipfs-shipyard/):** package this as a kind of "mobile SDK" on top of IPFS, similar to how peer-base relates to building dynamic data apps, or how ipfs-provider helps use multiple backends. Pros: loose coupling, lower integration overhead upfront. Cons: somewhat lower visibility, requires ongoing community stewardship.
- **Move into [ipfs core](https://github.com/ipfs/):** integrate more deeply into the core modules (required to be placed in ipfs org). Pros: potentially deeper integration, lower risk of APIs going out of sync, etc. Cons: upfront evaluation and integration cost, needs core maintainer time.

My suggestion is to move into ipfs-shipyard and make public ASAP, possibly even before merging #5. We saw some amazing energy around this application area at IPFS camp, and not letting it wither is very important. Having a visible place for the discussion of IPFS-on-mobile is a big win even without shipped code. However, It might be worth completing #2, or otherwise clarifying what this module will actually do.

(N.B. most *code* is currently in https://github.com/berty/gomobile-ipfs/pull/5, waiting on @gfanton to return from vacation)

**Comment by aeddi** [comment]
@alanshaw I can't transfer it directly to ipfs-shipyard because I'm not a member of the organization.
Can I transfer it to your account so you can forward it?

**Comment by alanshaw** [comment]
Sure!

**Comment by alanshaw** [comment]
Done, let me know who else to add to the team @aeddi

**Comment by aeddi** [comment]
@alanshaw Can you add @glouvigny, @moul and @gfanton please?
Thanks :)
