### ISSUE TITLE
Android example does not work

### ISSUE THREAD

**Issue by ThomasPluck** [ipfs-shipyard/gomobile-ipfs#74]
I've attempted to build and run the android example provided, and attempted to download the maven package using the repository listed in the .pom provided in the package on github.

Either way, the error:

`Could not GET 'https://dl.bintray.com/berty/gomobile-ipfs-android/ipfs/gomobile/core/0.0.42-dev/core-0.0.42-dev.pom'. Received status code 403 from server: Forbidden`

is thrown.

How do I resolve this? Thanks.

**Comment by aeddi** [comment]
Hello,
Since Bintray has been shutdown, the packages are no longer accessible, we are currently changing the release process to set up Github Packages, a PR should be available within the week.

**Comment by makeworld-the-better-one** [comment]
Any update on the packages? Looks like the last one was from July 2021

**Comment by cawfree** [comment]
@makeworld-the-better-one

I've setup a working build process here if you're interested:
https://github.com/cawfree/react-native-gomobile-ipfs
