### ISSUE TITLE
403 permission denied

### ISSUE THREAD

**Issue by zinete** [ipfs-shipyard/gomobile-ipfs#76]
![image](https://user-images.githubusercontent.com/23396979/126733855-6937a4f6-e643-4b9c-82d4-166b00de443d.png)

Unable to download dependencies ？？
[https://dl.bintray.com/berty/gomobile-ipfs-ios/bridge/1.2.1/bridge-1.2.1.zip](https://dl.bintray.com/berty/gomobile-ipfs-ios/bridge/1.2.1/bridge-1.2.1.zip)

**Comment by ThomasPluck** [comment]
Any update on this?

**Comment by jefft0** [comment]
Hello @zinete . Are you still seeing this error?

**Comment by jefft0** [comment]
No more comments from original poster.
