### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by Allenxuxu** [ipfs-shipyard/gomobile-ipfs#78]
Any plans to support flutter?

**Comment by Garciconx** [comment]
I have the same question, Greetings!

**Comment by jefft0** [comment]
We don't plan to support Flutter. (We already plan to support React-Native which is the most used framework for mobile development.) We encourage the community to create other packages. If you or someone else want to create a flutter package on separate repo, we can help you if you have questions by opening a new issue.
