### ISSUE TITLE
make build_core.android    error

### ISSUE THREAD

**Issue by minddewo** [ipfs-shipyard/gomobile-ipfs#79]
![1635738042(1)](https://user-images.githubusercontent.com/3061285/139618696-d78c194f-6a24-4e43-85e4-bf238174d011.png)
run  make build_core.android    error
 How to resolve this error?

**Comment by beilvla** [comment]
我也是运行这make build_core.android 错误  但是我的错误好像和你的不一样，希望你指导一下
![image](https://user-images.githubusercontent.com/34034894/149625834-a5f7956b-62f0-4a33-9f2a-ee1e8b78dd5c.png)

**Comment by beilvla** [comment]
ym@ymdeMacBook-Pro packages % make build_core.android
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
------------------------------------
      Go: installing modules        
------------------------------------
go mod download
go install golang.org/x/mobile/cmd/gomobile
go install golang.org/x/mobile/cmd/gobind
go run golang.org/x/mobile/cmd/gomobile init -v
panic: unsupported GOARCH: arm64

goroutine 1 [running]:
main.archNDK(...)
	/Users/ym/downloads/gopath/bin/pkg/mod/github.com/aeddi/mobile@v0.0.3-silicon/cmd/gomobile/env.go:339
main.(*ndkToolchain).Path(0x1400011bc90, {0x1400014a060, 0x28}, {0x1003b4931, 0x5})
	/Users/ym/downloads/gopath/bin/pkg/mod/github.com/aeddi/mobile@v0.0.3-silicon/cmd/gomobile/env.go:368 +0x78
main.envInit()
	/Users/ym/downloads/gopath/bin/pkg/mod/github.com/aeddi/mobile@v0.0.3-silicon/cmd/gomobile/env.go:142 +0x2f0
main.runInit(0x1006d0480)
	/Users/ym/downloads/gopath/bin/pkg/mod/github.com/aeddi/mobile@v0.0.3-silicon/cmd/gomobile/init.go:95 +0x558
main.main()
	/Users/ym/downloads/gopath/bin/pkg/mod/github.com/aeddi/mobile@v0.0.3-silicon/cmd/gomobile/main.go:73 +0x4b0
exit status 2
make: *** [go] Error 1
ym@ymdeMacBook-Pro packages %

**Comment by minddewo** [comment]
python版本不兼容，要换个



---Original---
From: ***@***.***&gt;
Date: Sat, Jan 15, 2022 22:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ipfs-shipyard/gomobile-ipfs] make build_core.android    error (Issue #79)




 
我也是运行这make build_core.android 错误  但是我的错误好像和你的不一样，希望你指导一下
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by beilvla** [comment]
这不是go么？换py做什么？

**Comment by minddewo** [comment]
太久没弄，记错了，我的错误当时是换了go版本解决的。



---Original---
From: ***@***.***&gt;
Date: Sat, Jan 15, 2022 22:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ipfs-shipyard/gomobile-ipfs] make build_core.android    error (Issue #79)




 
这不是go么？换py做什么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by beilvla** [comment]
换的go的版本么？还是换的AndroidNDK的版本之类的？

**Comment by minddewo** [comment]
你的错误和我的不一样，你试试换ndk版本吧，我没遇到你这个错误。我换了go版本直接就编译好了
，我是在ubuntu下编译的。

---Original---
From: ***@***.***&gt;
Date: Sat, Jan 15, 2022 22:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ipfs-shipyard/gomobile-ipfs] make build_core.android    error (Issue #79)




 
***@***.*** packages % make build_core.android
 fatal: not a git repository (or any of the parent directories): .git
 fatal: not a git repository (or any of the parent directories): .git
   Go: installing modules          
 
go mod download
 go install golang.org/x/mobile/cmd/gomobile
 go install golang.org/x/mobile/cmd/gobind
 go run golang.org/x/mobile/cmd/gomobile init -v
 panic: unsupported GOARCH: arm64
 
goroutine 1 [running]:
 main.archNDK(...)
 ***@***.***/cmd/gomobile/env.go:339
 main.(*ndkToolchain).Path(0x1400011bc90, {0x1400014a060, 0x28}, {0x1003b4931, 0x5})
 ***@***.***/cmd/gomobile/env.go:368 +0x78
 main.envInit()
 ***@***.***/cmd/gomobile/env.go:142 +0x2f0
 main.runInit(0x1006d0480)
 ***@***.***/cmd/gomobile/init.go:95 +0x558
 main.main()
 ***@***.***/cmd/gomobile/main.go:73 +0x4b0
 exit status 2
 make: *** [go] Error 1
 ***@***.*** packages %
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by beilvla** [comment]
好的 谢谢

**Comment by beilvla** [comment]
我把ndk版本改为21.4.7075529，还是同样的错误
![image](https://user-images.githubusercontent.com/34034894/149626334-c884d4c0-6302-491b-b2ee-94d5fcf31001.png)

**Comment by beilvla** [comment]
> > 我把ndk版本改为21.4.7075529，还是同样的错误
> 
> 怎么样，我core可以打包出来但是不知道如何用这个包创建Android的IPFS节点，它里面的.so文件我都不知道怎么用😅

我也不知道怎么创建ipfs节点

**Comment by ScienceNoBorders** [comment]
> 我也不知道怎么创建ipfs节点

你还在研究这个么，可以交流一下

**Comment by beilvla** [comment]
> > 我也不知道怎么创建ipfs节点
> 
> 你还在研究这个么，可以交流一下

可以啊

**Comment by ScienceNoBorders** [comment]
> 可以啊

[![Gitter](https://badges.gitter.im/ipfs-application/community.svg)](https://gitter.im/ipfs-application/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
来这吧

**Comment by jefft0** [comment]
Hello @minddewo . It looks like the discussion was moved to gitter. Has your issue been solved?

**Comment by minddewo** [comment]
@jefft0   I solved this issue  a year ago, change GO version ,you can have a try.

**Comment by jefft0** [comment]
Thank you for the reply. Closing this issue.
