### ISSUE TITLE
iOS Demo, Random XKCD report error.

### ISSUE THREAD

**Issue by DarknessFall** [ipfs-shipyard/gomobile-ipfs#90]
I install the iOS demo on my iPhone, the "Share file" and "Fetch file" worked very well. But the "Random XKCD" report error:
cat: could not resolve name.
![IMG_9754](https://user-images.githubusercontent.com/7892335/149900867-5f30cf3c-f82d-4f80-9c33-400b3d9df08d.PNG)

**Comment by jefft0** [comment]
Hello @DarknessFall . There have been many bug fixes since January 2022 which may have resolved your issue. Are you still seeing this bug? If there are no more questions, then in 21 days this issue will be closed as resolved.

**Comment by jefft0** [comment]
No more questions. Closing as resolved.
